# Generated by Django 3.0 on 2021-05-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityid', models.AutoField(db_column='CityID', primary_key=True, serialize=False)),
                ('postalcode', models.CharField(db_column='postalCode', max_length=50)),
                ('placename', models.CharField(db_column='PlaceName', max_length=50)),
                ('state', models.CharField(db_column='State', max_length=50)),
                ('stateabbr', models.CharField(db_column='StateAbbr', max_length=50)),
                ('lat_wgs84', models.DecimalField(db_column='LAT_wgs84', decimal_places=6, max_digits=9)),
                ('lon_wgs84', models.DecimalField(db_column='LON_wgs84', decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'City',
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guitarbrand',
            fields=[
                ('brandid', models.AutoField(db_column='BrandID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Guitar Brand',
                'db_table': 'GuitarBrand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listingpictureurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureurl', models.CharField(db_column='pictureURL', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Listing Picture URL',
                'db_table': 'ListingPictureURL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listingstatushistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('responseidchangedto', models.IntegerField(blank=True, db_column='ResponseIDchangedTo', null=True)),
                ('pricechangedfrom', models.DecimalField(blank=True, db_column='PriceChangedFrom', decimal_places=4, max_digits=19, null=True)),
                ('pricechangedto', models.DecimalField(blank=True, db_column='PriceChangedTo', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'verbose_name_plural': 'Listing Status History',
                'db_table': 'ListingStatusHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Luthierinteractionshist',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('interactiondate', models.DateTimeField(db_column='InteractionDate')),
                ('responseidchangedto', models.IntegerField(blank=True, db_column='ResponseIDchangedTo', null=True)),
                ('pricechangedfrom', models.DecimalField(blank=True, db_column='PriceChangedFrom', decimal_places=4, max_digits=19, null=True)),
                ('pricechangedto', models.DecimalField(blank=True, db_column='PriceChangedTo', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'verbose_name_plural': 'Luthier Interactions History',
                'db_table': 'LuthierInteractionsHist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Luthierservice',
            fields=[
                ('orderid', models.AutoField(db_column='OrderID', primary_key=True, serialize=False)),
                ('orderdate', models.DateField(db_column='OrderDate')),
                ('orderdeadline', models.DateField(db_column='OrderDeadline')),
                ('servicecost', models.DecimalField(blank=True, db_column='ServiceCost', decimal_places=4, max_digits=19, null=True)),
                ('luthierproblemdesc', models.TextField(blank=True, db_column='LuthierProblemDesc', null=True)),
            ],
            options={
                'verbose_name_plural': 'Luthier Service',
                'db_table': 'LuthierService',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productstatusresponses',
            fields=[
                ('statusid', models.IntegerField(db_column='StatusID', primary_key=True, serialize=False)),
                ('statusname', models.CharField(db_column='StatusName', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Product Status Responses',
                'db_table': 'ProductStatusResponses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userrole',
            fields=[
                ('roleid', models.IntegerField(db_column='RoleID', primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_column='RoleName', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'User Role',
                'db_table': 'UserRole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=50)),
                ('lastname', models.CharField(db_column='LastName', max_length=50)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('street_homeno', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
