# Generated by Django 3.0 on 2021-04-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listingpictureurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictureurl', models.CharField(db_column='pictureURL', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Listing Picture URL',
                'db_table': 'Listing Picture URL',
                'managed': False,
            },
        ),
    ]
