# Generated by Django 3.0 on 2021-04-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listingpictureurl'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='listingpictureurl',
            table='ListingPictureURL',
        ),
    ]
