# Generated by Django 3.0 on 2021-05-08 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categories_userlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlisting',
            name='listingdate',
            field=models.DateField(db_column='ListingDate', default=django.utils.timezone.now),
        ),
    ]
