# Generated by Django 3.0 on 2021-05-08 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210508_0226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='guitarbrand',
            options={'verbose_name_plural': 'Guitar Brand'},
        ),
        migrations.AlterModelOptions(
            name='listingpictureurl',
            options={'verbose_name_plural': 'Listing Picture URL'},
        ),
        migrations.AlterModelOptions(
            name='listingstatushistory',
            options={'verbose_name_plural': 'Listing Status History'},
        ),
        migrations.AlterModelOptions(
            name='luthierinteractionshist',
            options={'verbose_name_plural': 'Luthier Interactions History'},
        ),
        migrations.AlterModelOptions(
            name='luthierservice',
            options={'verbose_name_plural': 'Luthier Service'},
        ),
        migrations.AlterModelOptions(
            name='productstatusresponses',
            options={'verbose_name_plural': 'Product Status Responses'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name_plural': 'User Role'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
